#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include "cydevice_trm.h"

/* LCD_bSeg_LCD */
#define LCD_bSeg_LCD__COMMON_0 43u
#define LCD_bSeg_LCD__COMMON_1 11u
#define LCD_bSeg_LCD__COMMON_2 9u
#define LCD_bSeg_LCD__COMMON_3 10u
#define LCD_bSeg_LCD__CONTROL CYREG_LCD_CONTROL
#define LCD_bSeg_LCD__DATA00 CYREG_LCD_DATA00
#define LCD_bSeg_LCD__DATA01 CYREG_LCD_DATA01
#define LCD_bSeg_LCD__DATA02 CYREG_LCD_DATA02
#define LCD_bSeg_LCD__DATA03 CYREG_LCD_DATA03
#define LCD_bSeg_LCD__DATA04 CYREG_LCD_DATA04
#define LCD_bSeg_LCD__DATA05 CYREG_LCD_DATA05
#define LCD_bSeg_LCD__DATA06 CYREG_LCD_DATA06
#define LCD_bSeg_LCD__DATA07 CYREG_LCD_DATA07
#define LCD_bSeg_LCD__DATA10 CYREG_LCD_DATA10
#define LCD_bSeg_LCD__DATA11 CYREG_LCD_DATA11
#define LCD_bSeg_LCD__DATA12 CYREG_LCD_DATA12
#define LCD_bSeg_LCD__DATA13 CYREG_LCD_DATA13
#define LCD_bSeg_LCD__DATA14 CYREG_LCD_DATA14
#define LCD_bSeg_LCD__DATA15 CYREG_LCD_DATA15
#define LCD_bSeg_LCD__DATA16 CYREG_LCD_DATA16
#define LCD_bSeg_LCD__DATA17 CYREG_LCD_DATA17
#define LCD_bSeg_LCD__DIVIDER CYREG_LCD_DIVIDER
#define LCD_bSeg_LCD__ID CYREG_LCD_ID
#define LCD_bSeg_LCD__SEGMENT_0 16u
#define LCD_bSeg_LCD__SEGMENT_1 18u
#define LCD_bSeg_LCD__SEGMENT_2 19u
#define LCD_bSeg_LCD__SEGMENT_3 20u
#define LCD_bSeg_LCD__SEGMENT_4 21u
#define LCD_bSeg_LCD__SEGMENT_5 3u
#define LCD_bSeg_LCD__SEGMENT_6 2u
#define LCD_bSeg_LCD__SEGMENT_7 45u

/* LCD_Com */
#define LCD_Com__0__DR CYREG_GPIO_PRT5_DR
#define LCD_Com__0__DR_CLR CYREG_GPIO_PRT5_DR_CLR
#define LCD_Com__0__DR_INV CYREG_GPIO_PRT5_DR_INV
#define LCD_Com__0__DR_SET CYREG_GPIO_PRT5_DR_SET
#define LCD_Com__0__HSIOM CYREG_HSIOM_PORT_SEL5
#define LCD_Com__0__HSIOM_MASK 0x0000F000u
#define LCD_Com__0__HSIOM_SHIFT 12u
#define LCD_Com__0__INTCFG CYREG_GPIO_PRT5_INTR_CFG
#define LCD_Com__0__INTR CYREG_GPIO_PRT5_INTR
#define LCD_Com__0__INTR_CFG CYREG_GPIO_PRT5_INTR_CFG
#define LCD_Com__0__INTSTAT CYREG_GPIO_PRT5_INTR
#define LCD_Com__0__MASK 0x08u
#define LCD_Com__0__PC CYREG_GPIO_PRT5_PC
#define LCD_Com__0__PC2 CYREG_GPIO_PRT5_PC2
#define LCD_Com__0__PORT 5u
#define LCD_Com__0__PS CYREG_GPIO_PRT5_PS
#define LCD_Com__0__SHIFT 3
#define LCD_Com__1__DR CYREG_GPIO_PRT1_DR
#define LCD_Com__1__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define LCD_Com__1__DR_INV CYREG_GPIO_PRT1_DR_INV
#define LCD_Com__1__DR_SET CYREG_GPIO_PRT1_DR_SET
#define LCD_Com__1__HSIOM CYREG_HSIOM_PORT_SEL1
#define LCD_Com__1__HSIOM_MASK 0x0000F000u
#define LCD_Com__1__HSIOM_SHIFT 12u
#define LCD_Com__1__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define LCD_Com__1__INTR CYREG_GPIO_PRT1_INTR
#define LCD_Com__1__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define LCD_Com__1__INTSTAT CYREG_GPIO_PRT1_INTR
#define LCD_Com__1__MASK 0x08u
#define LCD_Com__1__OUT_SEL CYREG_UDB_PA1_CFG10
#define LCD_Com__1__OUT_SEL_SHIFT 6u
#define LCD_Com__1__OUT_SEL_VAL -1u
#define LCD_Com__1__PA__CFG0 CYREG_UDB_PA1_CFG0
#define LCD_Com__1__PA__CFG1 CYREG_UDB_PA1_CFG1
#define LCD_Com__1__PA__CFG10 CYREG_UDB_PA1_CFG10
#define LCD_Com__1__PA__CFG11 CYREG_UDB_PA1_CFG11
#define LCD_Com__1__PA__CFG12 CYREG_UDB_PA1_CFG12
#define LCD_Com__1__PA__CFG13 CYREG_UDB_PA1_CFG13
#define LCD_Com__1__PA__CFG14 CYREG_UDB_PA1_CFG14
#define LCD_Com__1__PA__CFG2 CYREG_UDB_PA1_CFG2
#define LCD_Com__1__PA__CFG3 CYREG_UDB_PA1_CFG3
#define LCD_Com__1__PA__CFG4 CYREG_UDB_PA1_CFG4
#define LCD_Com__1__PA__CFG5 CYREG_UDB_PA1_CFG5
#define LCD_Com__1__PA__CFG6 CYREG_UDB_PA1_CFG6
#define LCD_Com__1__PA__CFG7 CYREG_UDB_PA1_CFG7
#define LCD_Com__1__PA__CFG8 CYREG_UDB_PA1_CFG8
#define LCD_Com__1__PA__CFG9 CYREG_UDB_PA1_CFG9
#define LCD_Com__1__PC CYREG_GPIO_PRT1_PC
#define LCD_Com__1__PC2 CYREG_GPIO_PRT1_PC2
#define LCD_Com__1__PORT 1u
#define LCD_Com__1__PS CYREG_GPIO_PRT1_PS
#define LCD_Com__1__SHIFT 3
#define LCD_Com__2__DR CYREG_GPIO_PRT1_DR
#define LCD_Com__2__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define LCD_Com__2__DR_INV CYREG_GPIO_PRT1_DR_INV
#define LCD_Com__2__DR_SET CYREG_GPIO_PRT1_DR_SET
#define LCD_Com__2__HSIOM CYREG_HSIOM_PORT_SEL1
#define LCD_Com__2__HSIOM_MASK 0x000000F0u
#define LCD_Com__2__HSIOM_SHIFT 4u
#define LCD_Com__2__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define LCD_Com__2__INTR CYREG_GPIO_PRT1_INTR
#define LCD_Com__2__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define LCD_Com__2__INTSTAT CYREG_GPIO_PRT1_INTR
#define LCD_Com__2__MASK 0x02u
#define LCD_Com__2__OUT_SEL CYREG_UDB_PA1_CFG10
#define LCD_Com__2__OUT_SEL_SHIFT 2u
#define LCD_Com__2__OUT_SEL_VAL -1u
#define LCD_Com__2__PA__CFG0 CYREG_UDB_PA1_CFG0
#define LCD_Com__2__PA__CFG1 CYREG_UDB_PA1_CFG1
#define LCD_Com__2__PA__CFG10 CYREG_UDB_PA1_CFG10
#define LCD_Com__2__PA__CFG11 CYREG_UDB_PA1_CFG11
#define LCD_Com__2__PA__CFG12 CYREG_UDB_PA1_CFG12
#define LCD_Com__2__PA__CFG13 CYREG_UDB_PA1_CFG13
#define LCD_Com__2__PA__CFG14 CYREG_UDB_PA1_CFG14
#define LCD_Com__2__PA__CFG2 CYREG_UDB_PA1_CFG2
#define LCD_Com__2__PA__CFG3 CYREG_UDB_PA1_CFG3
#define LCD_Com__2__PA__CFG4 CYREG_UDB_PA1_CFG4
#define LCD_Com__2__PA__CFG5 CYREG_UDB_PA1_CFG5
#define LCD_Com__2__PA__CFG6 CYREG_UDB_PA1_CFG6
#define LCD_Com__2__PA__CFG7 CYREG_UDB_PA1_CFG7
#define LCD_Com__2__PA__CFG8 CYREG_UDB_PA1_CFG8
#define LCD_Com__2__PA__CFG9 CYREG_UDB_PA1_CFG9
#define LCD_Com__2__PC CYREG_GPIO_PRT1_PC
#define LCD_Com__2__PC2 CYREG_GPIO_PRT1_PC2
#define LCD_Com__2__PORT 1u
#define LCD_Com__2__PS CYREG_GPIO_PRT1_PS
#define LCD_Com__2__SHIFT 1
#define LCD_Com__3__DR CYREG_GPIO_PRT1_DR
#define LCD_Com__3__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define LCD_Com__3__DR_INV CYREG_GPIO_PRT1_DR_INV
#define LCD_Com__3__DR_SET CYREG_GPIO_PRT1_DR_SET
#define LCD_Com__3__HSIOM CYREG_HSIOM_PORT_SEL1
#define LCD_Com__3__HSIOM_MASK 0x00000F00u
#define LCD_Com__3__HSIOM_SHIFT 8u
#define LCD_Com__3__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define LCD_Com__3__INTR CYREG_GPIO_PRT1_INTR
#define LCD_Com__3__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define LCD_Com__3__INTSTAT CYREG_GPIO_PRT1_INTR
#define LCD_Com__3__MASK 0x04u
#define LCD_Com__3__OUT_SEL CYREG_UDB_PA1_CFG10
#define LCD_Com__3__OUT_SEL_SHIFT 4u
#define LCD_Com__3__OUT_SEL_VAL -1u
#define LCD_Com__3__PA__CFG0 CYREG_UDB_PA1_CFG0
#define LCD_Com__3__PA__CFG1 CYREG_UDB_PA1_CFG1
#define LCD_Com__3__PA__CFG10 CYREG_UDB_PA1_CFG10
#define LCD_Com__3__PA__CFG11 CYREG_UDB_PA1_CFG11
#define LCD_Com__3__PA__CFG12 CYREG_UDB_PA1_CFG12
#define LCD_Com__3__PA__CFG13 CYREG_UDB_PA1_CFG13
#define LCD_Com__3__PA__CFG14 CYREG_UDB_PA1_CFG14
#define LCD_Com__3__PA__CFG2 CYREG_UDB_PA1_CFG2
#define LCD_Com__3__PA__CFG3 CYREG_UDB_PA1_CFG3
#define LCD_Com__3__PA__CFG4 CYREG_UDB_PA1_CFG4
#define LCD_Com__3__PA__CFG5 CYREG_UDB_PA1_CFG5
#define LCD_Com__3__PA__CFG6 CYREG_UDB_PA1_CFG6
#define LCD_Com__3__PA__CFG7 CYREG_UDB_PA1_CFG7
#define LCD_Com__3__PA__CFG8 CYREG_UDB_PA1_CFG8
#define LCD_Com__3__PA__CFG9 CYREG_UDB_PA1_CFG9
#define LCD_Com__3__PC CYREG_GPIO_PRT1_PC
#define LCD_Com__3__PC2 CYREG_GPIO_PRT1_PC2
#define LCD_Com__3__PORT 1u
#define LCD_Com__3__PS CYREG_GPIO_PRT1_PS
#define LCD_Com__3__SHIFT 2

/* LCD_Seg */
#define LCD_Seg__0__DR CYREG_GPIO_PRT2_DR
#define LCD_Seg__0__DR_CLR CYREG_GPIO_PRT2_DR_CLR
#define LCD_Seg__0__DR_INV CYREG_GPIO_PRT2_DR_INV
#define LCD_Seg__0__DR_SET CYREG_GPIO_PRT2_DR_SET
#define LCD_Seg__0__HSIOM CYREG_HSIOM_PORT_SEL2
#define LCD_Seg__0__HSIOM_MASK 0x0000000Fu
#define LCD_Seg__0__HSIOM_SHIFT 0u
#define LCD_Seg__0__INTCFG CYREG_GPIO_PRT2_INTR_CFG
#define LCD_Seg__0__INTR CYREG_GPIO_PRT2_INTR
#define LCD_Seg__0__INTR_CFG CYREG_GPIO_PRT2_INTR_CFG
#define LCD_Seg__0__INTSTAT CYREG_GPIO_PRT2_INTR
#define LCD_Seg__0__MASK 0x01u
#define LCD_Seg__0__OUT_SEL CYREG_UDB_PA2_CFG10
#define LCD_Seg__0__OUT_SEL_SHIFT 0u
#define LCD_Seg__0__OUT_SEL_VAL -1u
#define LCD_Seg__0__PA__CFG0 CYREG_UDB_PA2_CFG0
#define LCD_Seg__0__PA__CFG1 CYREG_UDB_PA2_CFG1
#define LCD_Seg__0__PA__CFG10 CYREG_UDB_PA2_CFG10
#define LCD_Seg__0__PA__CFG11 CYREG_UDB_PA2_CFG11
#define LCD_Seg__0__PA__CFG12 CYREG_UDB_PA2_CFG12
#define LCD_Seg__0__PA__CFG13 CYREG_UDB_PA2_CFG13
#define LCD_Seg__0__PA__CFG14 CYREG_UDB_PA2_CFG14
#define LCD_Seg__0__PA__CFG2 CYREG_UDB_PA2_CFG2
#define LCD_Seg__0__PA__CFG3 CYREG_UDB_PA2_CFG3
#define LCD_Seg__0__PA__CFG4 CYREG_UDB_PA2_CFG4
#define LCD_Seg__0__PA__CFG5 CYREG_UDB_PA2_CFG5
#define LCD_Seg__0__PA__CFG6 CYREG_UDB_PA2_CFG6
#define LCD_Seg__0__PA__CFG7 CYREG_UDB_PA2_CFG7
#define LCD_Seg__0__PA__CFG8 CYREG_UDB_PA2_CFG8
#define LCD_Seg__0__PA__CFG9 CYREG_UDB_PA2_CFG9
#define LCD_Seg__0__PC CYREG_GPIO_PRT2_PC
#define LCD_Seg__0__PC2 CYREG_GPIO_PRT2_PC2
#define LCD_Seg__0__PORT 2u
#define LCD_Seg__0__PS CYREG_GPIO_PRT2_PS
#define LCD_Seg__0__SHIFT 0
#define LCD_Seg__1__DR CYREG_GPIO_PRT2_DR
#define LCD_Seg__1__DR_CLR CYREG_GPIO_PRT2_DR_CLR
#define LCD_Seg__1__DR_INV CYREG_GPIO_PRT2_DR_INV
#define LCD_Seg__1__DR_SET CYREG_GPIO_PRT2_DR_SET
#define LCD_Seg__1__HSIOM CYREG_HSIOM_PORT_SEL2
#define LCD_Seg__1__HSIOM_MASK 0x00000F00u
#define LCD_Seg__1__HSIOM_SHIFT 8u
#define LCD_Seg__1__INTCFG CYREG_GPIO_PRT2_INTR_CFG
#define LCD_Seg__1__INTR CYREG_GPIO_PRT2_INTR
#define LCD_Seg__1__INTR_CFG CYREG_GPIO_PRT2_INTR_CFG
#define LCD_Seg__1__INTSTAT CYREG_GPIO_PRT2_INTR
#define LCD_Seg__1__MASK 0x04u
#define LCD_Seg__1__OUT_SEL CYREG_UDB_PA2_CFG10
#define LCD_Seg__1__OUT_SEL_SHIFT 4u
#define LCD_Seg__1__OUT_SEL_VAL -1u
#define LCD_Seg__1__PA__CFG0 CYREG_UDB_PA2_CFG0
#define LCD_Seg__1__PA__CFG1 CYREG_UDB_PA2_CFG1
#define LCD_Seg__1__PA__CFG10 CYREG_UDB_PA2_CFG10
#define LCD_Seg__1__PA__CFG11 CYREG_UDB_PA2_CFG11
#define LCD_Seg__1__PA__CFG12 CYREG_UDB_PA2_CFG12
#define LCD_Seg__1__PA__CFG13 CYREG_UDB_PA2_CFG13
#define LCD_Seg__1__PA__CFG14 CYREG_UDB_PA2_CFG14
#define LCD_Seg__1__PA__CFG2 CYREG_UDB_PA2_CFG2
#define LCD_Seg__1__PA__CFG3 CYREG_UDB_PA2_CFG3
#define LCD_Seg__1__PA__CFG4 CYREG_UDB_PA2_CFG4
#define LCD_Seg__1__PA__CFG5 CYREG_UDB_PA2_CFG5
#define LCD_Seg__1__PA__CFG6 CYREG_UDB_PA2_CFG6
#define LCD_Seg__1__PA__CFG7 CYREG_UDB_PA2_CFG7
#define LCD_Seg__1__PA__CFG8 CYREG_UDB_PA2_CFG8
#define LCD_Seg__1__PA__CFG9 CYREG_UDB_PA2_CFG9
#define LCD_Seg__1__PC CYREG_GPIO_PRT2_PC
#define LCD_Seg__1__PC2 CYREG_GPIO_PRT2_PC2
#define LCD_Seg__1__PORT 2u
#define LCD_Seg__1__PS CYREG_GPIO_PRT2_PS
#define LCD_Seg__1__SHIFT 2
#define LCD_Seg__2__DR CYREG_GPIO_PRT2_DR
#define LCD_Seg__2__DR_CLR CYREG_GPIO_PRT2_DR_CLR
#define LCD_Seg__2__DR_INV CYREG_GPIO_PRT2_DR_INV
#define LCD_Seg__2__DR_SET CYREG_GPIO_PRT2_DR_SET
#define LCD_Seg__2__HSIOM CYREG_HSIOM_PORT_SEL2
#define LCD_Seg__2__HSIOM_MASK 0x0000F000u
#define LCD_Seg__2__HSIOM_SHIFT 12u
#define LCD_Seg__2__INTCFG CYREG_GPIO_PRT2_INTR_CFG
#define LCD_Seg__2__INTR CYREG_GPIO_PRT2_INTR
#define LCD_Seg__2__INTR_CFG CYREG_GPIO_PRT2_INTR_CFG
#define LCD_Seg__2__INTSTAT CYREG_GPIO_PRT2_INTR
#define LCD_Seg__2__MASK 0x08u
#define LCD_Seg__2__OUT_SEL CYREG_UDB_PA2_CFG10
#define LCD_Seg__2__OUT_SEL_SHIFT 6u
#define LCD_Seg__2__OUT_SEL_VAL -1u
#define LCD_Seg__2__PA__CFG0 CYREG_UDB_PA2_CFG0
#define LCD_Seg__2__PA__CFG1 CYREG_UDB_PA2_CFG1
#define LCD_Seg__2__PA__CFG10 CYREG_UDB_PA2_CFG10
#define LCD_Seg__2__PA__CFG11 CYREG_UDB_PA2_CFG11
#define LCD_Seg__2__PA__CFG12 CYREG_UDB_PA2_CFG12
#define LCD_Seg__2__PA__CFG13 CYREG_UDB_PA2_CFG13
#define LCD_Seg__2__PA__CFG14 CYREG_UDB_PA2_CFG14
#define LCD_Seg__2__PA__CFG2 CYREG_UDB_PA2_CFG2
#define LCD_Seg__2__PA__CFG3 CYREG_UDB_PA2_CFG3
#define LCD_Seg__2__PA__CFG4 CYREG_UDB_PA2_CFG4
#define LCD_Seg__2__PA__CFG5 CYREG_UDB_PA2_CFG5
#define LCD_Seg__2__PA__CFG6 CYREG_UDB_PA2_CFG6
#define LCD_Seg__2__PA__CFG7 CYREG_UDB_PA2_CFG7
#define LCD_Seg__2__PA__CFG8 CYREG_UDB_PA2_CFG8
#define LCD_Seg__2__PA__CFG9 CYREG_UDB_PA2_CFG9
#define LCD_Seg__2__PC CYREG_GPIO_PRT2_PC
#define LCD_Seg__2__PC2 CYREG_GPIO_PRT2_PC2
#define LCD_Seg__2__PORT 2u
#define LCD_Seg__2__PS CYREG_GPIO_PRT2_PS
#define LCD_Seg__2__SHIFT 3
#define LCD_Seg__3__DR CYREG_GPIO_PRT2_DR
#define LCD_Seg__3__DR_CLR CYREG_GPIO_PRT2_DR_CLR
#define LCD_Seg__3__DR_INV CYREG_GPIO_PRT2_DR_INV
#define LCD_Seg__3__DR_SET CYREG_GPIO_PRT2_DR_SET
#define LCD_Seg__3__HSIOM CYREG_HSIOM_PORT_SEL2
#define LCD_Seg__3__HSIOM_MASK 0x000F0000u
#define LCD_Seg__3__HSIOM_SHIFT 16u
#define LCD_Seg__3__INTCFG CYREG_GPIO_PRT2_INTR_CFG
#define LCD_Seg__3__INTR CYREG_GPIO_PRT2_INTR
#define LCD_Seg__3__INTR_CFG CYREG_GPIO_PRT2_INTR_CFG
#define LCD_Seg__3__INTSTAT CYREG_GPIO_PRT2_INTR
#define LCD_Seg__3__MASK 0x10u
#define LCD_Seg__3__OUT_SEL CYREG_UDB_PA2_CFG10
#define LCD_Seg__3__OUT_SEL_SHIFT 8u
#define LCD_Seg__3__OUT_SEL_VAL -1u
#define LCD_Seg__3__PA__CFG0 CYREG_UDB_PA2_CFG0
#define LCD_Seg__3__PA__CFG1 CYREG_UDB_PA2_CFG1
#define LCD_Seg__3__PA__CFG10 CYREG_UDB_PA2_CFG10
#define LCD_Seg__3__PA__CFG11 CYREG_UDB_PA2_CFG11
#define LCD_Seg__3__PA__CFG12 CYREG_UDB_PA2_CFG12
#define LCD_Seg__3__PA__CFG13 CYREG_UDB_PA2_CFG13
#define LCD_Seg__3__PA__CFG14 CYREG_UDB_PA2_CFG14
#define LCD_Seg__3__PA__CFG2 CYREG_UDB_PA2_CFG2
#define LCD_Seg__3__PA__CFG3 CYREG_UDB_PA2_CFG3
#define LCD_Seg__3__PA__CFG4 CYREG_UDB_PA2_CFG4
#define LCD_Seg__3__PA__CFG5 CYREG_UDB_PA2_CFG5
#define LCD_Seg__3__PA__CFG6 CYREG_UDB_PA2_CFG6
#define LCD_Seg__3__PA__CFG7 CYREG_UDB_PA2_CFG7
#define LCD_Seg__3__PA__CFG8 CYREG_UDB_PA2_CFG8
#define LCD_Seg__3__PA__CFG9 CYREG_UDB_PA2_CFG9
#define LCD_Seg__3__PC CYREG_GPIO_PRT2_PC
#define LCD_Seg__3__PC2 CYREG_GPIO_PRT2_PC2
#define LCD_Seg__3__PORT 2u
#define LCD_Seg__3__PS CYREG_GPIO_PRT2_PS
#define LCD_Seg__3__SHIFT 4
#define LCD_Seg__4__DR CYREG_GPIO_PRT2_DR
#define LCD_Seg__4__DR_CLR CYREG_GPIO_PRT2_DR_CLR
#define LCD_Seg__4__DR_INV CYREG_GPIO_PRT2_DR_INV
#define LCD_Seg__4__DR_SET CYREG_GPIO_PRT2_DR_SET
#define LCD_Seg__4__HSIOM CYREG_HSIOM_PORT_SEL2
#define LCD_Seg__4__HSIOM_MASK 0x00F00000u
#define LCD_Seg__4__HSIOM_SHIFT 20u
#define LCD_Seg__4__INTCFG CYREG_GPIO_PRT2_INTR_CFG
#define LCD_Seg__4__INTR CYREG_GPIO_PRT2_INTR
#define LCD_Seg__4__INTR_CFG CYREG_GPIO_PRT2_INTR_CFG
#define LCD_Seg__4__INTSTAT CYREG_GPIO_PRT2_INTR
#define LCD_Seg__4__MASK 0x20u
#define LCD_Seg__4__OUT_SEL CYREG_UDB_PA2_CFG11
#define LCD_Seg__4__OUT_SEL_SHIFT 10u
#define LCD_Seg__4__OUT_SEL_VAL -1u
#define LCD_Seg__4__PA__CFG0 CYREG_UDB_PA2_CFG0
#define LCD_Seg__4__PA__CFG1 CYREG_UDB_PA2_CFG1
#define LCD_Seg__4__PA__CFG10 CYREG_UDB_PA2_CFG10
#define LCD_Seg__4__PA__CFG11 CYREG_UDB_PA2_CFG11
#define LCD_Seg__4__PA__CFG12 CYREG_UDB_PA2_CFG12
#define LCD_Seg__4__PA__CFG13 CYREG_UDB_PA2_CFG13
#define LCD_Seg__4__PA__CFG14 CYREG_UDB_PA2_CFG14
#define LCD_Seg__4__PA__CFG2 CYREG_UDB_PA2_CFG2
#define LCD_Seg__4__PA__CFG3 CYREG_UDB_PA2_CFG3
#define LCD_Seg__4__PA__CFG4 CYREG_UDB_PA2_CFG4
#define LCD_Seg__4__PA__CFG5 CYREG_UDB_PA2_CFG5
#define LCD_Seg__4__PA__CFG6 CYREG_UDB_PA2_CFG6
#define LCD_Seg__4__PA__CFG7 CYREG_UDB_PA2_CFG7
#define LCD_Seg__4__PA__CFG8 CYREG_UDB_PA2_CFG8
#define LCD_Seg__4__PA__CFG9 CYREG_UDB_PA2_CFG9
#define LCD_Seg__4__PC CYREG_GPIO_PRT2_PC
#define LCD_Seg__4__PC2 CYREG_GPIO_PRT2_PC2
#define LCD_Seg__4__PORT 2u
#define LCD_Seg__4__PS CYREG_GPIO_PRT2_PS
#define LCD_Seg__4__SHIFT 5
#define LCD_Seg__5__DR CYREG_GPIO_PRT0_DR
#define LCD_Seg__5__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define LCD_Seg__5__DR_INV CYREG_GPIO_PRT0_DR_INV
#define LCD_Seg__5__DR_SET CYREG_GPIO_PRT0_DR_SET
#define LCD_Seg__5__HSIOM CYREG_HSIOM_PORT_SEL0
#define LCD_Seg__5__HSIOM_MASK 0x0000F000u
#define LCD_Seg__5__HSIOM_SHIFT 12u
#define LCD_Seg__5__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define LCD_Seg__5__INTR CYREG_GPIO_PRT0_INTR
#define LCD_Seg__5__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define LCD_Seg__5__INTSTAT CYREG_GPIO_PRT0_INTR
#define LCD_Seg__5__MASK 0x08u
#define LCD_Seg__5__OUT_SEL CYREG_UDB_PA0_CFG11
#define LCD_Seg__5__OUT_SEL_SHIFT 6u
#define LCD_Seg__5__OUT_SEL_VAL -1u
#define LCD_Seg__5__PA__CFG0 CYREG_UDB_PA0_CFG0
#define LCD_Seg__5__PA__CFG1 CYREG_UDB_PA0_CFG1
#define LCD_Seg__5__PA__CFG10 CYREG_UDB_PA0_CFG10
#define LCD_Seg__5__PA__CFG11 CYREG_UDB_PA0_CFG11
#define LCD_Seg__5__PA__CFG12 CYREG_UDB_PA0_CFG12
#define LCD_Seg__5__PA__CFG13 CYREG_UDB_PA0_CFG13
#define LCD_Seg__5__PA__CFG14 CYREG_UDB_PA0_CFG14
#define LCD_Seg__5__PA__CFG2 CYREG_UDB_PA0_CFG2
#define LCD_Seg__5__PA__CFG3 CYREG_UDB_PA0_CFG3
#define LCD_Seg__5__PA__CFG4 CYREG_UDB_PA0_CFG4
#define LCD_Seg__5__PA__CFG5 CYREG_UDB_PA0_CFG5
#define LCD_Seg__5__PA__CFG6 CYREG_UDB_PA0_CFG6
#define LCD_Seg__5__PA__CFG7 CYREG_UDB_PA0_CFG7
#define LCD_Seg__5__PA__CFG8 CYREG_UDB_PA0_CFG8
#define LCD_Seg__5__PA__CFG9 CYREG_UDB_PA0_CFG9
#define LCD_Seg__5__PC CYREG_GPIO_PRT0_PC
#define LCD_Seg__5__PC2 CYREG_GPIO_PRT0_PC2
#define LCD_Seg__5__PORT 0u
#define LCD_Seg__5__PS CYREG_GPIO_PRT0_PS
#define LCD_Seg__5__SHIFT 3
#define LCD_Seg__6__DR CYREG_GPIO_PRT0_DR
#define LCD_Seg__6__DR_CLR CYREG_GPIO_PRT0_DR_CLR
#define LCD_Seg__6__DR_INV CYREG_GPIO_PRT0_DR_INV
#define LCD_Seg__6__DR_SET CYREG_GPIO_PRT0_DR_SET
#define LCD_Seg__6__HSIOM CYREG_HSIOM_PORT_SEL0
#define LCD_Seg__6__HSIOM_MASK 0x00000F00u
#define LCD_Seg__6__HSIOM_SHIFT 8u
#define LCD_Seg__6__INTCFG CYREG_GPIO_PRT0_INTR_CFG
#define LCD_Seg__6__INTR CYREG_GPIO_PRT0_INTR
#define LCD_Seg__6__INTR_CFG CYREG_GPIO_PRT0_INTR_CFG
#define LCD_Seg__6__INTSTAT CYREG_GPIO_PRT0_INTR
#define LCD_Seg__6__MASK 0x04u
#define LCD_Seg__6__OUT_SEL CYREG_UDB_PA0_CFG11
#define LCD_Seg__6__OUT_SEL_SHIFT 4u
#define LCD_Seg__6__OUT_SEL_VAL -1u
#define LCD_Seg__6__PA__CFG0 CYREG_UDB_PA0_CFG0
#define LCD_Seg__6__PA__CFG1 CYREG_UDB_PA0_CFG1
#define LCD_Seg__6__PA__CFG10 CYREG_UDB_PA0_CFG10
#define LCD_Seg__6__PA__CFG11 CYREG_UDB_PA0_CFG11
#define LCD_Seg__6__PA__CFG12 CYREG_UDB_PA0_CFG12
#define LCD_Seg__6__PA__CFG13 CYREG_UDB_PA0_CFG13
#define LCD_Seg__6__PA__CFG14 CYREG_UDB_PA0_CFG14
#define LCD_Seg__6__PA__CFG2 CYREG_UDB_PA0_CFG2
#define LCD_Seg__6__PA__CFG3 CYREG_UDB_PA0_CFG3
#define LCD_Seg__6__PA__CFG4 CYREG_UDB_PA0_CFG4
#define LCD_Seg__6__PA__CFG5 CYREG_UDB_PA0_CFG5
#define LCD_Seg__6__PA__CFG6 CYREG_UDB_PA0_CFG6
#define LCD_Seg__6__PA__CFG7 CYREG_UDB_PA0_CFG7
#define LCD_Seg__6__PA__CFG8 CYREG_UDB_PA0_CFG8
#define LCD_Seg__6__PA__CFG9 CYREG_UDB_PA0_CFG9
#define LCD_Seg__6__PC CYREG_GPIO_PRT0_PC
#define LCD_Seg__6__PC2 CYREG_GPIO_PRT0_PC2
#define LCD_Seg__6__PORT 0u
#define LCD_Seg__6__PS CYREG_GPIO_PRT0_PS
#define LCD_Seg__6__SHIFT 2
#define LCD_Seg__7__DR CYREG_GPIO_PRT5_DR
#define LCD_Seg__7__DR_CLR CYREG_GPIO_PRT5_DR_CLR
#define LCD_Seg__7__DR_INV CYREG_GPIO_PRT5_DR_INV
#define LCD_Seg__7__DR_SET CYREG_GPIO_PRT5_DR_SET
#define LCD_Seg__7__HSIOM CYREG_HSIOM_PORT_SEL5
#define LCD_Seg__7__HSIOM_MASK 0x00F00000u
#define LCD_Seg__7__HSIOM_SHIFT 20u
#define LCD_Seg__7__INTCFG CYREG_GPIO_PRT5_INTR_CFG
#define LCD_Seg__7__INTR CYREG_GPIO_PRT5_INTR
#define LCD_Seg__7__INTR_CFG CYREG_GPIO_PRT5_INTR_CFG
#define LCD_Seg__7__INTSTAT CYREG_GPIO_PRT5_INTR
#define LCD_Seg__7__MASK 0x20u
#define LCD_Seg__7__PC CYREG_GPIO_PRT5_PC
#define LCD_Seg__7__PC2 CYREG_GPIO_PRT5_PC2
#define LCD_Seg__7__PORT 5u
#define LCD_Seg__7__PS CYREG_GPIO_PRT5_PS
#define LCD_Seg__7__SHIFT 5

/* led0 */
#define led0__0__DR CYREG_GPIO_PRT3_DR
#define led0__0__DR_CLR CYREG_GPIO_PRT3_DR_CLR
#define led0__0__DR_INV CYREG_GPIO_PRT3_DR_INV
#define led0__0__DR_SET CYREG_GPIO_PRT3_DR_SET
#define led0__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define led0__0__HSIOM_MASK 0x000000F0u
#define led0__0__HSIOM_SHIFT 4u
#define led0__0__INTCFG CYREG_GPIO_PRT3_INTR_CFG
#define led0__0__INTR CYREG_GPIO_PRT3_INTR
#define led0__0__INTR_CFG CYREG_GPIO_PRT3_INTR_CFG
#define led0__0__INTSTAT CYREG_GPIO_PRT3_INTR
#define led0__0__MASK 0x02u
#define led0__0__PA__CFG0 CYREG_UDB_PA3_CFG0
#define led0__0__PA__CFG1 CYREG_UDB_PA3_CFG1
#define led0__0__PA__CFG10 CYREG_UDB_PA3_CFG10
#define led0__0__PA__CFG11 CYREG_UDB_PA3_CFG11
#define led0__0__PA__CFG12 CYREG_UDB_PA3_CFG12
#define led0__0__PA__CFG13 CYREG_UDB_PA3_CFG13
#define led0__0__PA__CFG14 CYREG_UDB_PA3_CFG14
#define led0__0__PA__CFG2 CYREG_UDB_PA3_CFG2
#define led0__0__PA__CFG3 CYREG_UDB_PA3_CFG3
#define led0__0__PA__CFG4 CYREG_UDB_PA3_CFG4
#define led0__0__PA__CFG5 CYREG_UDB_PA3_CFG5
#define led0__0__PA__CFG6 CYREG_UDB_PA3_CFG6
#define led0__0__PA__CFG7 CYREG_UDB_PA3_CFG7
#define led0__0__PA__CFG8 CYREG_UDB_PA3_CFG8
#define led0__0__PA__CFG9 CYREG_UDB_PA3_CFG9
#define led0__0__PC CYREG_GPIO_PRT3_PC
#define led0__0__PC2 CYREG_GPIO_PRT3_PC2
#define led0__0__PORT 3u
#define led0__0__PS CYREG_GPIO_PRT3_PS
#define led0__0__SHIFT 1
#define led0__DR CYREG_GPIO_PRT3_DR
#define led0__DR_CLR CYREG_GPIO_PRT3_DR_CLR
#define led0__DR_INV CYREG_GPIO_PRT3_DR_INV
#define led0__DR_SET CYREG_GPIO_PRT3_DR_SET
#define led0__INTCFG CYREG_GPIO_PRT3_INTR_CFG
#define led0__INTR CYREG_GPIO_PRT3_INTR
#define led0__INTR_CFG CYREG_GPIO_PRT3_INTR_CFG
#define led0__INTSTAT CYREG_GPIO_PRT3_INTR
#define led0__MASK 0x02u
#define led0__PA__CFG0 CYREG_UDB_PA3_CFG0
#define led0__PA__CFG1 CYREG_UDB_PA3_CFG1
#define led0__PA__CFG10 CYREG_UDB_PA3_CFG10
#define led0__PA__CFG11 CYREG_UDB_PA3_CFG11
#define led0__PA__CFG12 CYREG_UDB_PA3_CFG12
#define led0__PA__CFG13 CYREG_UDB_PA3_CFG13
#define led0__PA__CFG14 CYREG_UDB_PA3_CFG14
#define led0__PA__CFG2 CYREG_UDB_PA3_CFG2
#define led0__PA__CFG3 CYREG_UDB_PA3_CFG3
#define led0__PA__CFG4 CYREG_UDB_PA3_CFG4
#define led0__PA__CFG5 CYREG_UDB_PA3_CFG5
#define led0__PA__CFG6 CYREG_UDB_PA3_CFG6
#define led0__PA__CFG7 CYREG_UDB_PA3_CFG7
#define led0__PA__CFG8 CYREG_UDB_PA3_CFG8
#define led0__PA__CFG9 CYREG_UDB_PA3_CFG9
#define led0__PC CYREG_GPIO_PRT3_PC
#define led0__PC2 CYREG_GPIO_PRT3_PC2
#define led0__PORT 3u
#define led0__PS CYREG_GPIO_PRT3_PS
#define led0__SHIFT 1

/* led1 */
#define led1__0__DR CYREG_GPIO_PRT3_DR
#define led1__0__DR_CLR CYREG_GPIO_PRT3_DR_CLR
#define led1__0__DR_INV CYREG_GPIO_PRT3_DR_INV
#define led1__0__DR_SET CYREG_GPIO_PRT3_DR_SET
#define led1__0__HSIOM CYREG_HSIOM_PORT_SEL3
#define led1__0__HSIOM_MASK 0x0000000Fu
#define led1__0__HSIOM_SHIFT 0u
#define led1__0__INTCFG CYREG_GPIO_PRT3_INTR_CFG
#define led1__0__INTR CYREG_GPIO_PRT3_INTR
#define led1__0__INTR_CFG CYREG_GPIO_PRT3_INTR_CFG
#define led1__0__INTSTAT CYREG_GPIO_PRT3_INTR
#define led1__0__MASK 0x01u
#define led1__0__PA__CFG0 CYREG_UDB_PA3_CFG0
#define led1__0__PA__CFG1 CYREG_UDB_PA3_CFG1
#define led1__0__PA__CFG10 CYREG_UDB_PA3_CFG10
#define led1__0__PA__CFG11 CYREG_UDB_PA3_CFG11
#define led1__0__PA__CFG12 CYREG_UDB_PA3_CFG12
#define led1__0__PA__CFG13 CYREG_UDB_PA3_CFG13
#define led1__0__PA__CFG14 CYREG_UDB_PA3_CFG14
#define led1__0__PA__CFG2 CYREG_UDB_PA3_CFG2
#define led1__0__PA__CFG3 CYREG_UDB_PA3_CFG3
#define led1__0__PA__CFG4 CYREG_UDB_PA3_CFG4
#define led1__0__PA__CFG5 CYREG_UDB_PA3_CFG5
#define led1__0__PA__CFG6 CYREG_UDB_PA3_CFG6
#define led1__0__PA__CFG7 CYREG_UDB_PA3_CFG7
#define led1__0__PA__CFG8 CYREG_UDB_PA3_CFG8
#define led1__0__PA__CFG9 CYREG_UDB_PA3_CFG9
#define led1__0__PC CYREG_GPIO_PRT3_PC
#define led1__0__PC2 CYREG_GPIO_PRT3_PC2
#define led1__0__PORT 3u
#define led1__0__PS CYREG_GPIO_PRT3_PS
#define led1__0__SHIFT 0
#define led1__DR CYREG_GPIO_PRT3_DR
#define led1__DR_CLR CYREG_GPIO_PRT3_DR_CLR
#define led1__DR_INV CYREG_GPIO_PRT3_DR_INV
#define led1__DR_SET CYREG_GPIO_PRT3_DR_SET
#define led1__INTCFG CYREG_GPIO_PRT3_INTR_CFG
#define led1__INTR CYREG_GPIO_PRT3_INTR
#define led1__INTR_CFG CYREG_GPIO_PRT3_INTR_CFG
#define led1__INTSTAT CYREG_GPIO_PRT3_INTR
#define led1__MASK 0x01u
#define led1__PA__CFG0 CYREG_UDB_PA3_CFG0
#define led1__PA__CFG1 CYREG_UDB_PA3_CFG1
#define led1__PA__CFG10 CYREG_UDB_PA3_CFG10
#define led1__PA__CFG11 CYREG_UDB_PA3_CFG11
#define led1__PA__CFG12 CYREG_UDB_PA3_CFG12
#define led1__PA__CFG13 CYREG_UDB_PA3_CFG13
#define led1__PA__CFG14 CYREG_UDB_PA3_CFG14
#define led1__PA__CFG2 CYREG_UDB_PA3_CFG2
#define led1__PA__CFG3 CYREG_UDB_PA3_CFG3
#define led1__PA__CFG4 CYREG_UDB_PA3_CFG4
#define led1__PA__CFG5 CYREG_UDB_PA3_CFG5
#define led1__PA__CFG6 CYREG_UDB_PA3_CFG6
#define led1__PA__CFG7 CYREG_UDB_PA3_CFG7
#define led1__PA__CFG8 CYREG_UDB_PA3_CFG8
#define led1__PA__CFG9 CYREG_UDB_PA3_CFG9
#define led1__PC CYREG_GPIO_PRT3_PC
#define led1__PC2 CYREG_GPIO_PRT3_PC2
#define led1__PORT 3u
#define led1__PS CYREG_GPIO_PRT3_PS
#define led1__SHIFT 0

/* Clock_1 */
#define Clock_1__CTRL_REGISTER CYREG_PERI_PCLK_CTL23
#define Clock_1__DIV_ID 0x00000042u
#define Clock_1__DIV_REGISTER CYREG_PERI_DIV_16_CTL2
#define Clock_1__PA_DIV_ID 0x000000FFu

/* capsense_Cmod */
#define capsense_Cmod__0__DR CYREG_GPIO_PRT4_DR
#define capsense_Cmod__0__DR_CLR CYREG_GPIO_PRT4_DR_CLR
#define capsense_Cmod__0__DR_INV CYREG_GPIO_PRT4_DR_INV
#define capsense_Cmod__0__DR_SET CYREG_GPIO_PRT4_DR_SET
#define capsense_Cmod__0__HSIOM CYREG_HSIOM_PORT_SEL4
#define capsense_Cmod__0__HSIOM_MASK 0x00000F00u
#define capsense_Cmod__0__HSIOM_SHIFT 8u
#define capsense_Cmod__0__INTCFG CYREG_GPIO_PRT4_INTR_CFG
#define capsense_Cmod__0__INTR CYREG_GPIO_PRT4_INTR
#define capsense_Cmod__0__INTR_CFG CYREG_GPIO_PRT4_INTR_CFG
#define capsense_Cmod__0__INTSTAT CYREG_GPIO_PRT4_INTR
#define capsense_Cmod__0__MASK 0x04u
#define capsense_Cmod__0__PC CYREG_GPIO_PRT4_PC
#define capsense_Cmod__0__PC2 CYREG_GPIO_PRT4_PC2
#define capsense_Cmod__0__PORT 4u
#define capsense_Cmod__0__PS CYREG_GPIO_PRT4_PS
#define capsense_Cmod__0__SHIFT 2
#define capsense_Cmod__Cmod__DR CYREG_GPIO_PRT4_DR
#define capsense_Cmod__Cmod__DR_CLR CYREG_GPIO_PRT4_DR_CLR
#define capsense_Cmod__Cmod__DR_INV CYREG_GPIO_PRT4_DR_INV
#define capsense_Cmod__Cmod__DR_SET CYREG_GPIO_PRT4_DR_SET
#define capsense_Cmod__Cmod__INTCFG CYREG_GPIO_PRT4_INTR_CFG
#define capsense_Cmod__Cmod__INTR CYREG_GPIO_PRT4_INTR
#define capsense_Cmod__Cmod__INTR_CFG CYREG_GPIO_PRT4_INTR_CFG
#define capsense_Cmod__Cmod__INTSTAT CYREG_GPIO_PRT4_INTR
#define capsense_Cmod__Cmod__MASK 0x04u
#define capsense_Cmod__Cmod__PC CYREG_GPIO_PRT4_PC
#define capsense_Cmod__Cmod__PC2 CYREG_GPIO_PRT4_PC2
#define capsense_Cmod__Cmod__PORT 4u
#define capsense_Cmod__Cmod__PS CYREG_GPIO_PRT4_PS
#define capsense_Cmod__Cmod__SHIFT 2
#define capsense_Cmod__DR CYREG_GPIO_PRT4_DR
#define capsense_Cmod__DR_CLR CYREG_GPIO_PRT4_DR_CLR
#define capsense_Cmod__DR_INV CYREG_GPIO_PRT4_DR_INV
#define capsense_Cmod__DR_SET CYREG_GPIO_PRT4_DR_SET
#define capsense_Cmod__INTCFG CYREG_GPIO_PRT4_INTR_CFG
#define capsense_Cmod__INTR CYREG_GPIO_PRT4_INTR
#define capsense_Cmod__INTR_CFG CYREG_GPIO_PRT4_INTR_CFG
#define capsense_Cmod__INTSTAT CYREG_GPIO_PRT4_INTR
#define capsense_Cmod__MASK 0x04u
#define capsense_Cmod__PC CYREG_GPIO_PRT4_PC
#define capsense_Cmod__PC2 CYREG_GPIO_PRT4_PC2
#define capsense_Cmod__PORT 4u
#define capsense_Cmod__PS CYREG_GPIO_PRT4_PS
#define capsense_Cmod__SHIFT 2

/* capsense_CSD_FFB */
#define capsense_CSD_FFB__CSD_CONFIG CYREG_CSD0_CONFIG
#define capsense_CSD_FFB__CSD_COUNTER CYREG_CSD0_COUNTER
#define capsense_CSD_FFB__CSD_ID CYREG_CSD0_ID
#define capsense_CSD_FFB__CSD_INTR CYREG_CSD0_INTR
#define capsense_CSD_FFB__CSD_INTR_SET CYREG_CSD0_INTR_SET
#define capsense_CSD_FFB__CSD_NUMBER 0u
#define capsense_CSD_FFB__CSD_PWM CYREG_CSD0_PWM
#define capsense_CSD_FFB__CSD_STATUS CYREG_CSD0_STATUS

/* capsense_IDAC1_cy_psoc4_idac */
#define capsense_IDAC1_cy_psoc4_idac__CONTROL CYREG_CSD0_CONFIG
#define capsense_IDAC1_cy_psoc4_idac__CSD_IDAC CYREG_CSD0_IDAC
#define capsense_IDAC1_cy_psoc4_idac__CSD_IDAC_SHIFT 0
#define capsense_IDAC1_cy_psoc4_idac__CSD_TRIM1 CYREG_CSD0_TRIM1
#define capsense_IDAC1_cy_psoc4_idac__CSD_TRIM1_SHIFT 0
#define capsense_IDAC1_cy_psoc4_idac__CSD_TRIM2 CYREG_CSD0_TRIM2
#define capsense_IDAC1_cy_psoc4_idac__CSD_TRIM2_SHIFT 0
#define capsense_IDAC1_cy_psoc4_idac__IDAC_NUMBER 1u
#define capsense_IDAC1_cy_psoc4_idac__POLARITY CYREG_CSD0_CONFIG
#define capsense_IDAC1_cy_psoc4_idac__POLARITY_SHIFT 16

/* capsense_IDAC2_cy_psoc4_idac */
#define capsense_IDAC2_cy_psoc4_idac__CONTROL CYREG_CSD0_CONFIG
#define capsense_IDAC2_cy_psoc4_idac__CSD_IDAC CYREG_CSD0_IDAC
#define capsense_IDAC2_cy_psoc4_idac__CSD_IDAC_SHIFT 16
#define capsense_IDAC2_cy_psoc4_idac__CSD_TRIM1 CYREG_CSD0_TRIM1
#define capsense_IDAC2_cy_psoc4_idac__CSD_TRIM1_SHIFT 4
#define capsense_IDAC2_cy_psoc4_idac__CSD_TRIM2 CYREG_CSD0_TRIM2
#define capsense_IDAC2_cy_psoc4_idac__CSD_TRIM2_SHIFT 4
#define capsense_IDAC2_cy_psoc4_idac__IDAC_NUMBER 2u
#define capsense_IDAC2_cy_psoc4_idac__POLARITY CYREG_CSD0_CONFIG
#define capsense_IDAC2_cy_psoc4_idac__POLARITY_SHIFT 17

/* capsense_ISR */
#define capsense_ISR__INTC_CLR_EN_REG CYREG_CM0_ICER
#define capsense_ISR__INTC_CLR_PD_REG CYREG_CM0_ICPR
#define capsense_ISR__INTC_MASK 0x20000u
#define capsense_ISR__INTC_NUMBER 17u
#define capsense_ISR__INTC_PRIOR_MASK 0xC000u
#define capsense_ISR__INTC_PRIOR_NUM 3u
#define capsense_ISR__INTC_PRIOR_REG CYREG_CM0_IPR4
#define capsense_ISR__INTC_SET_EN_REG CYREG_CM0_ISER
#define capsense_ISR__INTC_SET_PD_REG CYREG_CM0_ISPR

/* capsense_SampleClk */
#define capsense_SampleClk__CTRL_REGISTER CYREG_PERI_PCLK_CTL7
#define capsense_SampleClk__DIV_ID 0x00000040u
#define capsense_SampleClk__DIV_REGISTER CYREG_PERI_DIV_16_CTL0
#define capsense_SampleClk__PA_DIV_ID 0x000000FFu

/* capsense_SenseClk */
#define capsense_SenseClk__CTRL_REGISTER CYREG_PERI_PCLK_CTL6
#define capsense_SenseClk__DIV_ID 0x00000041u
#define capsense_SenseClk__DIV_REGISTER CYREG_PERI_DIV_16_CTL1
#define capsense_SenseClk__PA_DIV_ID 0x000000FFu

/* capsense_Sns */
#define capsense_Sns__0__DR CYREG_GPIO_PRT1_DR
#define capsense_Sns__0__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define capsense_Sns__0__DR_INV CYREG_GPIO_PRT1_DR_INV
#define capsense_Sns__0__DR_SET CYREG_GPIO_PRT1_DR_SET
#define capsense_Sns__0__HSIOM CYREG_HSIOM_PORT_SEL1
#define capsense_Sns__0__HSIOM_MASK 0x0000000Fu
#define capsense_Sns__0__HSIOM_SHIFT 0u
#define capsense_Sns__0__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define capsense_Sns__0__INTR CYREG_GPIO_PRT1_INTR
#define capsense_Sns__0__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define capsense_Sns__0__INTSTAT CYREG_GPIO_PRT1_INTR
#define capsense_Sns__0__MASK 0x01u
#define capsense_Sns__0__PA__CFG0 CYREG_UDB_PA1_CFG0
#define capsense_Sns__0__PA__CFG1 CYREG_UDB_PA1_CFG1
#define capsense_Sns__0__PA__CFG10 CYREG_UDB_PA1_CFG10
#define capsense_Sns__0__PA__CFG11 CYREG_UDB_PA1_CFG11
#define capsense_Sns__0__PA__CFG12 CYREG_UDB_PA1_CFG12
#define capsense_Sns__0__PA__CFG13 CYREG_UDB_PA1_CFG13
#define capsense_Sns__0__PA__CFG14 CYREG_UDB_PA1_CFG14
#define capsense_Sns__0__PA__CFG2 CYREG_UDB_PA1_CFG2
#define capsense_Sns__0__PA__CFG3 CYREG_UDB_PA1_CFG3
#define capsense_Sns__0__PA__CFG4 CYREG_UDB_PA1_CFG4
#define capsense_Sns__0__PA__CFG5 CYREG_UDB_PA1_CFG5
#define capsense_Sns__0__PA__CFG6 CYREG_UDB_PA1_CFG6
#define capsense_Sns__0__PA__CFG7 CYREG_UDB_PA1_CFG7
#define capsense_Sns__0__PA__CFG8 CYREG_UDB_PA1_CFG8
#define capsense_Sns__0__PA__CFG9 CYREG_UDB_PA1_CFG9
#define capsense_Sns__0__PC CYREG_GPIO_PRT1_PC
#define capsense_Sns__0__PC2 CYREG_GPIO_PRT1_PC2
#define capsense_Sns__0__PORT 1u
#define capsense_Sns__0__PS CYREG_GPIO_PRT1_PS
#define capsense_Sns__0__SHIFT 0
#define capsense_Sns__1__DR CYREG_GPIO_PRT2_DR
#define capsense_Sns__1__DR_CLR CYREG_GPIO_PRT2_DR_CLR
#define capsense_Sns__1__DR_INV CYREG_GPIO_PRT2_DR_INV
#define capsense_Sns__1__DR_SET CYREG_GPIO_PRT2_DR_SET
#define capsense_Sns__1__HSIOM CYREG_HSIOM_PORT_SEL2
#define capsense_Sns__1__HSIOM_MASK 0xF0000000u
#define capsense_Sns__1__HSIOM_SHIFT 28u
#define capsense_Sns__1__INTCFG CYREG_GPIO_PRT2_INTR_CFG
#define capsense_Sns__1__INTR CYREG_GPIO_PRT2_INTR
#define capsense_Sns__1__INTR_CFG CYREG_GPIO_PRT2_INTR_CFG
#define capsense_Sns__1__INTSTAT CYREG_GPIO_PRT2_INTR
#define capsense_Sns__1__MASK 0x80u
#define capsense_Sns__1__PA__CFG0 CYREG_UDB_PA2_CFG0
#define capsense_Sns__1__PA__CFG1 CYREG_UDB_PA2_CFG1
#define capsense_Sns__1__PA__CFG10 CYREG_UDB_PA2_CFG10
#define capsense_Sns__1__PA__CFG11 CYREG_UDB_PA2_CFG11
#define capsense_Sns__1__PA__CFG12 CYREG_UDB_PA2_CFG12
#define capsense_Sns__1__PA__CFG13 CYREG_UDB_PA2_CFG13
#define capsense_Sns__1__PA__CFG14 CYREG_UDB_PA2_CFG14
#define capsense_Sns__1__PA__CFG2 CYREG_UDB_PA2_CFG2
#define capsense_Sns__1__PA__CFG3 CYREG_UDB_PA2_CFG3
#define capsense_Sns__1__PA__CFG4 CYREG_UDB_PA2_CFG4
#define capsense_Sns__1__PA__CFG5 CYREG_UDB_PA2_CFG5
#define capsense_Sns__1__PA__CFG6 CYREG_UDB_PA2_CFG6
#define capsense_Sns__1__PA__CFG7 CYREG_UDB_PA2_CFG7
#define capsense_Sns__1__PA__CFG8 CYREG_UDB_PA2_CFG8
#define capsense_Sns__1__PA__CFG9 CYREG_UDB_PA2_CFG9
#define capsense_Sns__1__PC CYREG_GPIO_PRT2_PC
#define capsense_Sns__1__PC2 CYREG_GPIO_PRT2_PC2
#define capsense_Sns__1__PORT 2u
#define capsense_Sns__1__PS CYREG_GPIO_PRT2_PS
#define capsense_Sns__1__SHIFT 7
#define capsense_Sns__Button0__BTN__DR CYREG_GPIO_PRT1_DR
#define capsense_Sns__Button0__BTN__DR_CLR CYREG_GPIO_PRT1_DR_CLR
#define capsense_Sns__Button0__BTN__DR_INV CYREG_GPIO_PRT1_DR_INV
#define capsense_Sns__Button0__BTN__DR_SET CYREG_GPIO_PRT1_DR_SET
#define capsense_Sns__Button0__BTN__INTCFG CYREG_GPIO_PRT1_INTR_CFG
#define capsense_Sns__Button0__BTN__INTR CYREG_GPIO_PRT1_INTR
#define capsense_Sns__Button0__BTN__INTR_CFG CYREG_GPIO_PRT1_INTR_CFG
#define capsense_Sns__Button0__BTN__INTSTAT CYREG_GPIO_PRT1_INTR
#define capsense_Sns__Button0__BTN__MASK 0x01u
#define capsense_Sns__Button0__BTN__PA__CFG0 CYREG_UDB_PA1_CFG0
#define capsense_Sns__Button0__BTN__PA__CFG1 CYREG_UDB_PA1_CFG1
#define capsense_Sns__Button0__BTN__PA__CFG10 CYREG_UDB_PA1_CFG10
#define capsense_Sns__Button0__BTN__PA__CFG11 CYREG_UDB_PA1_CFG11
#define capsense_Sns__Button0__BTN__PA__CFG12 CYREG_UDB_PA1_CFG12
#define capsense_Sns__Button0__BTN__PA__CFG13 CYREG_UDB_PA1_CFG13
#define capsense_Sns__Button0__BTN__PA__CFG14 CYREG_UDB_PA1_CFG14
#define capsense_Sns__Button0__BTN__PA__CFG2 CYREG_UDB_PA1_CFG2
#define capsense_Sns__Button0__BTN__PA__CFG3 CYREG_UDB_PA1_CFG3
#define capsense_Sns__Button0__BTN__PA__CFG4 CYREG_UDB_PA1_CFG4
#define capsense_Sns__Button0__BTN__PA__CFG5 CYREG_UDB_PA1_CFG5
#define capsense_Sns__Button0__BTN__PA__CFG6 CYREG_UDB_PA1_CFG6
#define capsense_Sns__Button0__BTN__PA__CFG7 CYREG_UDB_PA1_CFG7
#define capsense_Sns__Button0__BTN__PA__CFG8 CYREG_UDB_PA1_CFG8
#define capsense_Sns__Button0__BTN__PA__CFG9 CYREG_UDB_PA1_CFG9
#define capsense_Sns__Button0__BTN__PC CYREG_GPIO_PRT1_PC
#define capsense_Sns__Button0__BTN__PC2 CYREG_GPIO_PRT1_PC2
#define capsense_Sns__Button0__BTN__PORT 1u
#define capsense_Sns__Button0__BTN__PS CYREG_GPIO_PRT1_PS
#define capsense_Sns__Button0__BTN__SHIFT 0
#define capsense_Sns__Button1__BTN__DR CYREG_GPIO_PRT2_DR
#define capsense_Sns__Button1__BTN__DR_CLR CYREG_GPIO_PRT2_DR_CLR
#define capsense_Sns__Button1__BTN__DR_INV CYREG_GPIO_PRT2_DR_INV
#define capsense_Sns__Button1__BTN__DR_SET CYREG_GPIO_PRT2_DR_SET
#define capsense_Sns__Button1__BTN__INTCFG CYREG_GPIO_PRT2_INTR_CFG
#define capsense_Sns__Button1__BTN__INTR CYREG_GPIO_PRT2_INTR
#define capsense_Sns__Button1__BTN__INTR_CFG CYREG_GPIO_PRT2_INTR_CFG
#define capsense_Sns__Button1__BTN__INTSTAT CYREG_GPIO_PRT2_INTR
#define capsense_Sns__Button1__BTN__MASK 0x80u
#define capsense_Sns__Button1__BTN__PA__CFG0 CYREG_UDB_PA2_CFG0
#define capsense_Sns__Button1__BTN__PA__CFG1 CYREG_UDB_PA2_CFG1
#define capsense_Sns__Button1__BTN__PA__CFG10 CYREG_UDB_PA2_CFG10
#define capsense_Sns__Button1__BTN__PA__CFG11 CYREG_UDB_PA2_CFG11
#define capsense_Sns__Button1__BTN__PA__CFG12 CYREG_UDB_PA2_CFG12
#define capsense_Sns__Button1__BTN__PA__CFG13 CYREG_UDB_PA2_CFG13
#define capsense_Sns__Button1__BTN__PA__CFG14 CYREG_UDB_PA2_CFG14
#define capsense_Sns__Button1__BTN__PA__CFG2 CYREG_UDB_PA2_CFG2
#define capsense_Sns__Button1__BTN__PA__CFG3 CYREG_UDB_PA2_CFG3
#define capsense_Sns__Button1__BTN__PA__CFG4 CYREG_UDB_PA2_CFG4
#define capsense_Sns__Button1__BTN__PA__CFG5 CYREG_UDB_PA2_CFG5
#define capsense_Sns__Button1__BTN__PA__CFG6 CYREG_UDB_PA2_CFG6
#define capsense_Sns__Button1__BTN__PA__CFG7 CYREG_UDB_PA2_CFG7
#define capsense_Sns__Button1__BTN__PA__CFG8 CYREG_UDB_PA2_CFG8
#define capsense_Sns__Button1__BTN__PA__CFG9 CYREG_UDB_PA2_CFG9
#define capsense_Sns__Button1__BTN__PC CYREG_GPIO_PRT2_PC
#define capsense_Sns__Button1__BTN__PC2 CYREG_GPIO_PRT2_PC2
#define capsense_Sns__Button1__BTN__PORT 2u
#define capsense_Sns__Button1__BTN__PS CYREG_GPIO_PRT2_PS
#define capsense_Sns__Button1__BTN__SHIFT 7

/* Miscellaneous */
#define CY_PROJECT_NAME "testlcd"
#define CY_VERSION "PSoC Creator  3.3 CP2"
#define CYDEV_BCLK__HFCLK__HZ 24000000U
#define CYDEV_BCLK__HFCLK__KHZ 24000U
#define CYDEV_BCLK__HFCLK__MHZ 24U
#define CYDEV_BCLK__SYSCLK__HZ 24000000U
#define CYDEV_BCLK__SYSCLK__KHZ 24000U
#define CYDEV_BCLK__SYSCLK__MHZ 24U
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 18u
#define CYDEV_CHIP_DIE_PSOC4A 10u
#define CYDEV_CHIP_DIE_PSOC5LP 17u
#define CYDEV_CHIP_DIE_TMA4 2u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC4
#define CYDEV_CHIP_JTAG_ID 0x110D11A1u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 10u
#define CYDEV_CHIP_MEMBER_4C 15u
#define CYDEV_CHIP_MEMBER_4D 6u
#define CYDEV_CHIP_MEMBER_4E 4u
#define CYDEV_CHIP_MEMBER_4F 11u
#define CYDEV_CHIP_MEMBER_4G 2u
#define CYDEV_CHIP_MEMBER_4H 9u
#define CYDEV_CHIP_MEMBER_4I 14u
#define CYDEV_CHIP_MEMBER_4J 7u
#define CYDEV_CHIP_MEMBER_4K 8u
#define CYDEV_CHIP_MEMBER_4L 13u
#define CYDEV_CHIP_MEMBER_4M 12u
#define CYDEV_CHIP_MEMBER_4N 5u
#define CYDEV_CHIP_MEMBER_4U 3u
#define CYDEV_CHIP_MEMBER_5A 17u
#define CYDEV_CHIP_MEMBER_5B 16u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_4M
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_MEMBER_USED
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REV_TMA4_ES 17u
#define CYDEV_CHIP_REV_TMA4_ES2 33u
#define CYDEV_CHIP_REV_TMA4_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4C_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4D_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4E_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256DMA 0u
#define CYDEV_CHIP_REVISION_4F_PRODUCTION_256K 0u
#define CYDEV_CHIP_REVISION_4G_ES 17u
#define CYDEV_CHIP_REVISION_4G_ES2 33u
#define CYDEV_CHIP_REVISION_4G_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_4H_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4I_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4J_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4K_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4L_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4M_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4N_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_4U_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_4M_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REVISION_USED
#define CYDEV_CONFIG_READ_ACCELERATOR 1
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_DEBUG_PROTECT_KILL 4
#define CYDEV_DEBUG_PROTECT_OPEN 1
#define CYDEV_DEBUG_PROTECT CYDEV_DEBUG_PROTECT_OPEN
#define CYDEV_DEBUG_PROTECT_PROTECTED 2
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_DFT_SELECT_CLK0 10u
#define CYDEV_DFT_SELECT_CLK1 11u
#define CYDEV_DMA_CHANNELS_AVAILABLE 8
#define CYDEV_HEAP_SIZE 0x80
#define CYDEV_IMO_TRIMMED_BY_USB 0u
#define CYDEV_IMO_TRIMMED_BY_WCO 0u
#define CYDEV_INTR_NUMBER_DMA 13u
#define CYDEV_IS_EXPORTING_CODE 0
#define CYDEV_IS_IMPORTING_CODE 0
#define CYDEV_PROJ_TYPE 0
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LAUNCHER 5
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_LOADABLEANDBOOTLOADER 4
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_STACK_SIZE 0x0800
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 1
#define CYDEV_VDDA 3.3
#define CYDEV_VDDA_MV 3300
#define CYDEV_VDDD 3.3
#define CYDEV_VDDD_MV 3300
#define CYDEV_VDDIO 3.3
#define CYDEV_VDDIO_MV 3300
#define CYDEV_WDT_GENERATE_ISR 1u
#define CYIPBLOCK_m0s8cpussv2_VERSION 1
#define CYIPBLOCK_m0s8csd_VERSION 1
#define CYIPBLOCK_m0s8ioss_VERSION 1
#define CYIPBLOCK_m0s8lcd_VERSION 2
#define CYIPBLOCK_m0s8lpcomp_VERSION 2
#define CYIPBLOCK_m0s8peri_VERSION 1
#define CYIPBLOCK_m0s8scb_VERSION 2
#define CYIPBLOCK_m0s8srssv2_VERSION 1
#define CYIPBLOCK_m0s8tcpwm_VERSION 2
#define CYIPBLOCK_m0s8udbif_VERSION 1
#define CYIPBLOCK_m0s8wco_VERSION 1
#define CYIPBLOCK_s8pass4al_VERSION 1
#define DMA_CHANNELS_USED__MASK 0u
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
