/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 Nightly Build 9582
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "blue.h"
#include "blue_aliases.h"
#include "BLEIOT_UART.h"
#include "BLEIOT_UART_SPI_UART.h"
#include "BLEIOT_UART_PINS.h"
#include "BLEIOT_UART_SPI_UART_PVT.h"
#include "BLEIOT_UART_PVT.h"
#include "BLEIOT_UART_BOOT.h"
#include "BLE_gatt.h"
#include "BLE.h"
#include "BLE_HAL_PVT.h"
#include "BLE_STACK_PVT.h"
#include "BLE_StackGap.h"
#include "BLE_StackGatt.h"
#include "BLE_StackGattDb.h"
#include "BLE_StackHostMain.h"
#include "BLE_StackL2cap.h"
#include "BLE_StackGattServer.h"
#include "BLE_StackGattClient.h"
#include "BLE_Stack.h"
#include "BLE_eventHandler.h"
#include "BLE_custom.h"
#include "PWM.h"
#include "Clock_1.h"
#include "EZI2C.h"
#include "EZI2C_PINS.h"
#include "EZI2C_PVT.h"
#include "EZI2C_EZI2C.h"
#include "EZI2C_EZI2C_PVT.h"
#include "EZI2C_BOOT.h"
#include "Bootloadable.h"
#include "BLEIOT_UART_SCBCLK.h"
#include "BLEIOT_UART_tx.h"
#include "BLEIOT_UART_tx_aliases.h"
#include "BLEIOT_UART_SCB_IRQ.h"
#include "BLEIOT_UART_rx.h"
#include "BLEIOT_UART_rx_aliases.h"
#include "BLE_bless_isr.h"
#include "EZI2C_SCBCLK.h"
#include "EZI2C_sda.h"
#include "EZI2C_sda_aliases.h"
#include "EZI2C_scl.h"
#include "EZI2C_scl_aliases.h"
#include "EZI2C_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

